Use shared libs
lunasolutions/googletest pull request #6
Opened 2018-01-09 00:04 UTC by daranday

2018-01-09 00:22 UTC, FrankieLi reviewed
Umm... it says all checks failed? Should it build in Jenkins?

2018-01-09 00:25 UTC, daranday commented
@FrankieLi Yep I'm trying to debug.

2018-01-16 21:56 UTC, FrankieLi approved these changes
Talked in person. Looks good to me.

2018-01-17 01:28 UTC, oselivanov requested changes

2018-01-17 01:28 UTC, oselivanov commented on Jenkinsfile
> +    ditto_utils.checkReleaseBranch(git_info.branch, version)
This is broken, no such function.

2018-01-17 19:32 UTC, daranday commented on Jenkinsfile
> +    ditto_utils.checkReleaseBranch(git_info.branch, version)
Fixed!

2018-01-17 20:06 UTC, oselivanov approved these changes
Checked, Jenkinsfile part, lgtm

2018-01-17 20:06 UTC, oselivanov commented on Jenkinsfile
> +      stage("Install from ${platform} repo and test") {
Installing

2018-01-17 20:06 UTC, oselivanov commented on Jenkinsfile
> +  stage("Build and Publish to Test") {
Building and publishing

2018-01-17 20:06 UTC, oselivanov commented on Jenkinsfile
> +      stage("Building and publishing dev revision ${platform}") {
Building and publishing ${platform} dev revision

2018-01-17 20:06 UTC, oselivanov commented on Jenkinsfile
> +  stage("Clean up") {
Cleaning up

2018-01-17 20:13 UTC, daranday commented on Jenkinsfile
> +      stage("Building and publishing dev revision ${platform}") {
Done

2018-01-17 20:13 UTC, daranday commented on Jenkinsfile
> +      stage("Install from ${platform} repo and test") {
done

2018-01-17 20:13 UTC, daranday commented on Jenkinsfile
> +  stage("Build and Publish to Test") {
done

2018-01-17 20:13 UTC, daranday commented on Jenkinsfile
> +  stage("Clean up") {
done

2018-01-17 23:58 UTC, oselivanov commented
Ship it!

2018-01-18 00:48 UTC, merged